FROM gliderlabs/alpine:3.3

WORKDIR /app

RUN echo "@edge http://dl-4.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories
RUN apk --update --no-cache add build-base elixir@edge erlang-crypto \
    erlang-parsetools erlang-syntax-tools erlang-dev inotify-tools \
    postgresql-client

ARG mix_env=prod
ARG phoenix_secret=not_set
ARG tls_key_path=not_set
ARG tls_cert_path=not_set
ARG fb_app_id=not_set
ARG fb_secret=not_set

ENV MIX_ENV=$mix_env
ENV PHOENIX_SECRET=$phoenix_secret
ENV TLS_KEY_PATH=$tls_key_path
ENV TLS_CERT_PATH=$tls_cert_path
ENV FB_APP_ID=$fb_app_id
ENV FB_SECRET=$fb_secret

RUN mix local.hex --force && mix local.rebar

COPY mix.exs /app
COPY mix.lock /app

COPY config /app/config
COPY lib /app/lib
COPY web /app/web

RUN mix deps.get && mix deps.compile

RUN mix compile

VOLUME /app/deps

CMD mix phoenix.server
