FROM node:5.8.0

VOLUME /var/build/input
VOLUME /var/build/output

WORKDIR /var/build

COPY package.json /var/build

COPY deps/phoenix /var/build/deps/phoenix
COPY deps/phoenix_html /var/build/deps/phoenix_html

COPY webpack.config.js /var/build
COPY tsconfig.json  /var/build
COPY typings.json  /var/build
COPY tslint.json /var/build
COPY .eslintrc.js /var/build
COPY .stylelintrc /var/build

RUN npm install
RUN npm run postinstall
RUN npm install -g webpack

CMD npm run dev
